name = "Jude"
uuid = "fde21e18-e93c-494f-95d6-786978d112c4"
authors = ["ardy-monaghan <ross.monaghan99@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
PortAudio = "80ea8bcb-4634-5cb3-8ee8-a132660d1d2d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
Waveforms = "cb13b1c6-351e-5134-b3ad-d6a530956a82"

[compat]
HTTP = "1.10.19"
PortAudio = "1.3.0"
Revise = "3.12.0"
Statistics = "1.11.1"
WAV = "1.2.0"
Waveforms = "0.1.3"
